.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/spin/schemas/appliance
	install -pm 644 bootiso.rng $(DESTDIR)/usr/share/spin/schemas/appliance/bootiso.rng
	install -pm 644 comps.rng $(DESTDIR)/usr/share/spin/schemas/appliance/comps.rng
	install -pm 644 config-rpm.rng $(DESTDIR)/usr/share/spin/schemas/appliance/config-rpm.rng
	install -pm 644 diskboot-image.rng $(DESTDIR)/usr/share/spin/schemas/appliance/diskboot-image.rng
	install -pm 644 gpgsign.rng $(DESTDIR)/usr/share/spin/schemas/appliance/gpgsign.rng
	install -pm 644 iso.rng $(DESTDIR)/usr/share/spin/schemas/appliance/iso.rng
	install -pm 644 kickstart.rng $(DESTDIR)/usr/share/spin/schemas/appliance/kickstart.rng
	install -pm 644 lib.rng $(DESTDIR)/usr/share/spin/schemas/appliance/lib.rng
	install -pm 644 logos-rpm.rng $(DESTDIR)/usr/share/spin/schemas/appliance/logos-rpm.rng
	install -pm 644 main.rng $(DESTDIR)/usr/share/spin/schemas/appliance/main.rng
	install -pm 644 product-image.rng $(DESTDIR)/usr/share/spin/schemas/appliance/product-image.rng
	install -pm 644 publish.rng $(DESTDIR)/usr/share/spin/schemas/appliance/publish.rng
	install -pm 644 release-files.rng $(DESTDIR)/usr/share/spin/schemas/appliance/release-files.rng
	install -pm 644 release-rpm.rng $(DESTDIR)/usr/share/spin/schemas/appliance/release-rpm.rng
	install -pm 644 repos.rng $(DESTDIR)/usr/share/spin/schemas/appliance/repos.rng
	install -pm 644 rpmbuild.rng $(DESTDIR)/usr/share/spin/schemas/appliance/rpmbuild.rng
	install -pm 644 sources.rng $(DESTDIR)/usr/share/spin/schemas/appliance/sources.rng
	install -pm 644 updates-image.rng $(DESTDIR)/usr/share/spin/schemas/appliance/updates-image.rng

clean:
