#!/bin/bash
#
# Script to run dimsbuild using files from subversion workspace.
# Useful for testing dimsbuild prior to rpm creation/release.
#
# Basic operation includes these steps:
# * Set PYTHONPATH
# * Set --conf-path=conf/ (can be overridden from the command line)
# * Set --lib-path=lib/ (can be overridden from the command line)
# * Execute bin/dimsbuild

# change to correct directory to ensure relative pathing works
cd `dirname $0`

export PYTHONPATH=lib/:../../trunk/dims-common/libs/python

while [ $# -gt 0 ]; do
  case $1 in
      --conf-path)        CONF_PATH=$2;         shift;;
      --lib-path)         LIB_PATH=$2;          shift;;
      *) EXTRA_ARGS="$EXTRA_ARGS $1";;
    esac
    shift
  done

[ ! $CONF_PATH ] && CONF_PATH=./conf/
[ ! $LIB_PATH ] && LIB_PATH=./lib/

chmod +x bin/dimsbuild
bin/dimsbuild --conf-path $CONF_PATH --lib-path $LIB_PATH $EXTRA_ARGS
