.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/systembuilder/schemas/system
	install -pm 644 bootiso.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/bootiso.rng
	install -pm 644 chroot.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/chroot.rng
	install -pm 644 config.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/config.rng
	install -pm 644 diskboot-image.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/diskboot-image.rng
	install -pm 644 gpgsign.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/gpgsign.rng
	install -pm 644 iso.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/iso.rng
	install -pm 644 kickstart.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/kickstart.rng
	install -pm 644 lib.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/lib.rng
	install -pm 644 main.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/main.rng
	install -pm 644 packages.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/packages.rng
	install -pm 644 product-image.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/product-image.rng
	install -pm 644 publish.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/publish.rng
	install -pm 644 release-files.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/release-files.rng
	install -pm 644 repos.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/repos.rng
	install -pm 644 rpmbuild.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/rpmbuild.rng
	install -pm 644 sources.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/sources.rng
	install -pm 644 updates-image.rng $(DESTDIR)/usr/share/systembuilder/schemas/system/updates-image.rng

clean:
