.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/spin/logos-rpm/files/kdisplay
	install -pm 644 Spin.kcsrc $(DESTDIR)/usr/share/spin/logos-rpm/files/kdisplay/Spin.kcsrc
	install -pm 644 SpinKDM.kcsrc $(DESTDIR)/usr/share/spin/logos-rpm/files/kdisplay/SpinKDM.kcsrc

clean:
