.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/kdisplay
	install -pm 644 SystemBuilder.kcsrc $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/kdisplay/SystemBuilder.kcsrc
	install -pm 644 SystemBuilderKDM.kcsrc $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/kdisplay/SystemBuilderKDM.kcsrc

clean:
