.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/solutionstudio/schemas/solution
	install -pm 644 bootiso.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/bootiso.rng
	install -pm 644 chroot.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/chroot.rng
	install -pm 644 config.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/config.rng
	install -pm 644 diskboot-image.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/diskboot-image.rng
	install -pm 644 gpgsign.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/gpgsign.rng
	install -pm 644 iso.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/iso.rng
	install -pm 644 kickstart.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/kickstart.rng
	install -pm 644 lib.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/lib.rng
	install -pm 644 main.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/main.rng
	install -pm 644 packages.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/packages.rng
	install -pm 644 product-image.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/product-image.rng
	install -pm 644 publish.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/publish.rng
	install -pm 644 release-files.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/release-files.rng
	install -pm 644 repos.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/repos.rng
	install -pm 644 rpmbuild.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/rpmbuild.rng
	install -pm 644 sources.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/sources.rng
	install -pm 644 updates-image.rng $(DESTDIR)/usr/share/solutionstudio/schemas/solution/updates-image.rng

clean:
