.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/systembuilder/schemas/logos-rpm
	install -pm 644 config.rng $(DESTDIR)/usr/share/systembuilder/schemas/logos-rpm/config.rng

clean:
