.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/systembuilder/schemas/distribution
	install -pm 644 bootiso.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/bootiso.rng
	install -pm 644 chroot.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/chroot.rng
	install -pm 644 config.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/config.rng
	install -pm 644 diskboot-image.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/diskboot-image.rng
	install -pm 644 gpgsign.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/gpgsign.rng
	install -pm 644 iso.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/iso.rng
	install -pm 644 kickstart.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/kickstart.rng
	install -pm 644 lib.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/lib.rng
	install -pm 644 main.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/main.rng
	install -pm 644 packages.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/packages.rng
	install -pm 644 product-image.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/product-image.rng
	install -pm 644 publish.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/publish.rng
	install -pm 644 release-files.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/release-files.rng
	install -pm 644 repos.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/repos.rng
	install -pm 644 rpmbuild.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/rpmbuild.rng
	install -pm 644 sources.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/sources.rng
	install -pm 644 updates-image.rng $(DESTDIR)/usr/share/systembuilder/schemas/distribution/updates-image.rng

clean:
