.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/ksplash
	install -pm 644 Theme.rc $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/ksplash/Theme.rc

clean:
