.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/backgrounds
	install -pm 644 desktop-backgrounds-systembuilder.xml $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/backgrounds/desktop-backgrounds-systembuilder.xml
	install -pm 644 systembuilder.xml $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/backgrounds/systembuilder.xml


clean:
