.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/spin/logos-rpm/files/backgrounds
	install -pm 644 desktop-backgrounds-spin.xml $(DESTDIR)/usr/share/spin/logos-rpm/files/backgrounds/desktop-backgrounds-spin.xml
	install -pm 644 spin.xml $(DESTDIR)/usr/share/spin/logos-rpm/files/backgrounds/spin.xml


clean:
