import dims.filereader as filereader

from dims.osutils import basename, dirname, mkdir
from event import EVENT_TYPE_MDLR, EVENT_TYPE_PROC
from interface import EventInterface, LocalsMixin
from lib import RpmHandler, RpmsInterface, addHandler, getHandler
from os.path import exists, join
from output import MorphStructMixin, tree

EVENTS = [
  {
    'id': 'release',
    'interface': 'RpmsInterface',
    'properties': EVENT_TYPE_PROC|EVENT_TYPE_MDLR,
    'provides': ['release-rpm'],
    'parent': 'RPMS',
  },    
]

#-------------- METADATA STRUCTS ---------#
RELEASE_MD_STRUCT = {
  'config': [
    '//main/fullname/text()',
    '//main/version/text()',
    '//release-rpm',    
    '//stores/*/store/gpgkey/text()',
    '//main/signing/publickey/text()',
  ],
  'input': [
    '//release-rpm/yum-repo/path/text()',
    '//stores/*/store/gpgkey/text()',
    '//main/signing/publickey/text()',
    '//release-rpm/eula/text()',
    '//release-rpm/other/text()',
  ],
  'output': [
    'os/release-rpm/',
  ],   
}

#------ HOOK FUNCTIONS ------#
def prerelease_hook(interface):
  handler = ReleaseRpmHandler(interface, RELEASE_MD_STRUCT)
  addHandler(handler, 'release')
  interface.disableEvent('release')
  if interface.pre(handler) or (interface.eventForceStatus('release') or False):
    interface.enableEvent('release')
        
def release_hook(interface):
  interface.log(0, "processing release")
  handler = getHandler('release')
  interface.modify(handler)

def postrelease_hook(interface):
  handler = getHandler('release')
  if handler.create:
    # add rpms to the included-packages control var, so that
    # they are added to the comps.xml
    interface.append_cvar('included-packages', [handler.rpmname])    
    # add rpms to the excluded-packages control var, so that
    # they are removed from the comps.xml
    interface.append_cvar('excluded-packages', handler.obsoletes.split())

#---------- HANDLERS -------------#
class ReleaseRpmHandler(RpmHandler, MorphStructMixin):
  def __init__(self, interface, data):
    # expand the xpath queries in the data struct
    MorphStructMixin.__init__(self, interface.config)
    
    RpmHandler.__init__(self, interface, data,
                        elementname='release-rpm',
                        rpmname='%s-release' %(interface.product,),
                        provides_test='redhat-release',
                        provides='redhat-release',
                        obsoletes = 'fedora-release redhat-release '
                                    'centos-release redhat-release-notes '
                                    'fedora-release-notes '
                                    'centos-release-notes',
                        description='distribution release files',
                        long_description='distribution release files; '
                          'autogenerated by dimsbuild')
    
    if self.data.has_key('input'):
      self.expandInput(self.data)
    if self.data.has_key('output'):      
      self.expandOutput(self.data, dirname(self.software_store)) # the 'output' element has entries
                                                                 # relative to dirname(software_store)
    
    self.prefix = dirname(self.software_store) # prefix to the directories in data['output']
    
    if not exists(self.software_store):
      mkdir(self.software_store, parent=True)    

  def _generate(self):
    # generate the .repo files if required
    pass

  def _get_data_files(self):
    # create the files that are installed in the /etc/ folder
    # and add the data_files entry for it, all the other
    # files are installed at /usr/share/release-notes.
    etc_files = self._create_etc_files()
    manifest = join(self.output_location, 'MANIFEST')
    f = open(manifest, 'w')
    f.write('setup.py\n')
    f.write('setup.cfg\n')
    files = tree(self.output_location, type='f|l', prefix=False)
    for file in files:
      f.write('%s\n' %(file,))
    f.close()
    config_option = '/usr/share/%s-release-notes-%s :' %(self.product, self.version,)
    rnotes_files = filter(lambda x: x not in etc_files and x != 'MANIFEST', files)
    rtn = ''
    if rnotes_files:
      value = ', '.join(rnotes_files)      
      rtn = ''.join([rtn, config_option, value, '\n\t'])
    if etc_files:
      rtn = ''.join([rtn, '/etc : ', ', '.join(etc_files)])
    return rtn

  def _create_etc_files(self):
    release_string = ['%s %s' %(self.fullname, self.version,)]
    issue_string = ['Kernel \\r on an \\m\n']

    # write the product-release and redhat-release files
    filereader.write(release_string, join(self.output_location, 'redhat-release'))
    filereader.write(release_string, join(self.output_location, '%s-release' %(self.product,)))
    
    # write the issue and issue.net files
    filereader.write(release_string+issue_string, join(self.output_location, 'issue'))    
    filereader.write(release_string+issue_string, join(self.output_location, 'issue.net'))
    
    return ['redhat-release', '%s-release' %(self.product,), 'issue', 'issue.net']
    
