.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/spin/logos-rpm/files/kdm
	install -pm 644 GdmGreeterTheme.desktop $(DESTDIR)/usr/share/spin/logos-rpm/files/kdm/GdmGreeterTheme.desktop
	install -pm 644 SpinKDM.xml $(DESTDIR)/usr/share/spin/logos-rpm/files/kdm/SpinKDM.xml

clean:
