.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/openprovision/schemas/system
	install -pm 644 bootiso.rng $(DESTDIR)/usr/share/openprovision/schemas/system/bootiso.rng
	install -pm 644 chroot.rng $(DESTDIR)/usr/share/openprovision/schemas/system/chroot.rng
	install -pm 644 config.rng $(DESTDIR)/usr/share/openprovision/schemas/system/config.rng
	install -pm 644 deploy.rng $(DESTDIR)/usr/share/openprovision/schemas/system/deploy.rng
	install -pm 644 diskboot-image.rng $(DESTDIR)/usr/share/openprovision/schemas/system/diskboot-image.rng
	install -pm 644 iso.rng $(DESTDIR)/usr/share/openprovision/schemas/system/iso.rng
	install -pm 644 kickstart.rng $(DESTDIR)/usr/share/openprovision/schemas/system/kickstart.rng
	install -pm 644 lib.rng $(DESTDIR)/usr/share/openprovision/schemas/system/lib.rng
	install -pm 644 main.rng $(DESTDIR)/usr/share/openprovision/schemas/system/main.rng
	install -pm 644 packages.rng $(DESTDIR)/usr/share/openprovision/schemas/system/packages.rng
	install -pm 644 publish.rng $(DESTDIR)/usr/share/openprovision/schemas/system/publish.rng
	install -pm 644 repos.rng $(DESTDIR)/usr/share/openprovision/schemas/system/repos.rng
	install -pm 644 rpmbuild.rng $(DESTDIR)/usr/share/openprovision/schemas/system/rpmbuild.rng
	install -pm 644 test.rng $(DESTDIR)/usr/share/openprovision/schemas/system/test.rng

clean:
