.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/spin/logos-rpm/files/gnome-background-properties
	install -pm 644 desktop-backgrounds-spin.xml $(DESTDIR)/usr/share/spin/logos-rpm/files/gnome-background-properties/desktop-backgrounds-spin.xml

clean:

