.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/spin/logos-rpm/icons
	install -pm 644 disconnect-active.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/disconnect-active.png
	install -pm 644 disconnect.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/disconnect.png
	install -pm 644 disconnect-prelight.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/disconnect-prelight.png
	install -pm 644 halt-active.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/halt-active.png
	install -pm 644 halt.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/halt.png
	install -pm 644 halt-prelight.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/halt-prelight.png
	install -pm 644 language-active.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/language-active.png
	install -pm 644 language.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/language.png
	install -pm 644 language-prelight.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/language-prelight.png
	install -pm 644 line.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/line.png
	install -pm 644 quit-active.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/quit-active.png
	install -pm 644 quit.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/quit.png
	install -pm 644 quit-prelight.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/quit-prelight.png
	install -pm 644 reboot-active.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/reboot-active.png
	install -pm 644 reboot.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/reboot.png
	install -pm 644 reboot-prelight.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/reboot-prelight.png
	install -pm 644 selection-active.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/selection-active.png
	install -pm 644 selection.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/selection.png
	install -pm 644 selection-prelight.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/selection-prelight.png
	install -pm 644 session-active.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/session-active.png
	install -pm 644 session.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/session.png
	install -pm 644 session-prelight.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/session-prelight.png
	install -pm 644 suspend-active.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/suspend-active.png
	install -pm 644 suspend.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/suspend.png
	install -pm 644 suspend-prelight.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/suspend-prelight.png
	install -pm 644 system-active.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/system-active.png
	install -pm 644 system.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/system.png
	install -pm 644 system-prelight.png $(DESTDIR)/usr/share/spin/logos-rpm/icons/system-prelight.png

clean:
