.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/spin/logos-rpm/fonts
	install -pm 644 DejaVuLGCSans-Bold.ttf $(DESTDIR)/usr/share/spin/logos-rpm/fonts/DejaVuLGCSans-Bold.ttf
	install -pm 644 DejaVuLGCSans-ExtraLight.ttf $(DESTDIR)/usr/share/spin/logos-rpm/fonts/DejaVuLGCSans-ExtraLight.ttf
	install -pm 644 DejaVuLGCSans.ttf $(DESTDIR)/usr/share/spin/logos-rpm/fonts/DejaVuLGCSans.ttf

clean:

