5.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/spin/logos-rpm/files/gnome-screensaver
	install -pm 644 lock-dialog-system.glade $(DESTDIR)/usr/share/spin/logos-rpm/files/gnome-screensaver/lock-dialog-system.glade
	install -pm 644 lock-dialog-system.gtkrc $(DESTDIR)/usr/share/spin/logos-rpm/files/gnome-screensaver/lock-dialog-system.gtkrc

clean:
