.PHONY: all clean install

all:

install:
	mkdir -p $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/gnome-background-properties
	install -pm 644 desktop-backgrounds-systembuilder.xml $(DESTDIR)/usr/share/systembuilder/logos-rpm/files/gnome-background-properties/desktop-backgrounds-systembuilder.xml

clean:

